---
title: "Fairfax BRT GTFS Frequency Analysis - Stations"
output_dir: "docs"  
output: 
    html_document:
        theme: flatly
        toc: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(dplyr)
library(sf)
library(tmap)
library(kableExtra)

tmap_mode("view")

knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)

```

## Mapping Station Frequency - Build and No Build

```{r fig.height=10, fig.width=9}

build_stations <- st_read("K:\\Projects\\Fairfax\\Features\\MMA\\GTFS\\peak_transit_build_station_frequency.shp", quiet = T) %>% 
  select(stop_desc, NumTrips, TripsPerHr, MaxWaitTm) %>% 
  arrange(TripsPerHr) %>% 
  st_transform(2283)

nobuild_stations <- st_read("K:\\Projects\\Fairfax\\Features\\MMA\\GTFS\\peak_transit_nobuild_station_frequency.shp", quiet = T) %>% 
  select(stop_desc, NumTrips, TripsPerHr, MaxWaitTm) %>% 
  arrange(TripsPerHr) %>% 
  st_transform(2283)

build <- tm_shape(build_stations) + 
  tm_dots(col = "TripsPerHr", breaks = c(0, 2, 4, 7, 10, 13, 20, 100), palette = "viridis", size = 0.03, title = "Build Trips/Hr") +
  tm_basemap("CartoDB.DarkMatter")
  
nobuild <- tm_shape(nobuild_stations) + 
  tm_dots(col = "TripsPerHr", breaks = c(0, 2, 4, 7, 10, 13, 20, 100), palette = "viridis", size = 0.03, title = "No Build Trips/Hr") +
  tm_basemap("CartoDB.DarkMatter")

tmap_arrange(nobuild, build, ncol = 2, sync = TRUE)

```


```{r}

corridor <- st_read("K:\\Projects\\Fairfax\\Features\\Transp\\ProposedRichmondHwyBRTroute\\ProposedRichmondHwyBRTroute.shp") %>% 
  st_transform(2283) %>% 
  st_buffer(1320)

build_corridor_stations <- st_filter(build_stations, corridor, .predicate = st_intersects) %>% 
  st_drop_geometry() %>% 
  arrange(desc(TripsPerHr))

## Build Station Frequency - Corridor Only

kbl(build_corridor_stations)%>%
  kable_paper("hover", full_width = F)

nobuild_corridor_stations <- st_filter(nobuild_stations, corridor, .predicate = st_intersects) %>% 
  st_drop_geometry() %>% 
  arrange(desc(TripsPerHr))

## No Build Station Frequency - Corridor Only

kbl(build_corridor_stations)%>%
  kable_paper("hover", full_width = F)
```

